/**
 * VANTRA COLLECTIVE — TRENDING CREATORS ROSTER
 * Auto-generated by scripts/refresh-creators.mjs — do not edit by hand.
 * To change creators or static fields, edit scripts/creators-config.json.
 * Last refreshed: 2026-07-01T09:38:19.906Z
 */

export const LAST_UPDATED = 'July 2026';

export const TRENDING_CREATORS = [
  {
    featured:   true,
    handle:     "@juno.makes",
    name:       "Juno Reyes",
    category:   "Lifestyle & Beauty",
    platform:   "TT",
    followers:  "284K",
    engagement: "9.8%",
    tags:       ["GRWM","Skincare","Day in My Life"],
    verified:   true,
    accent:     "#E07B91",
  },

  {
    handle:     "@theo.lifts",
    name:       "Theo Bracken",
    category:   "Fitness & Physique",
    platform:   "TT",
    followers:  "162K",
    engagement: "12.1%",
    tags:       ["Strength Training","Mindset","Progress"],
    verified:   true,
    accent:     "#5BA3FF",
  },

  {
    handle:     "@mira.codes",
    name:       "Mira Solberg",
    category:   "Tech & Reviews",
    platform:   "YT",
    followers:  "97K",
    engagement: "7.4%",
    tags:       ["Gadgets","Productivity","Honest Reviews"],
    verified:   true,
    accent:     "#9B72FF",
  },

  {
    handle:     "@finntheflavor",
    name:       "Finn Okafor",
    category:   "Food & Culinary",
    platform:   "TT",
    followers:  "356K",
    engagement: "10.6%",
    tags:       ["Home Cooking","Budget Meals","Quick Recipes"],
    verified:   true,
    accent:     "#F0A535",
  },

  {
    handle:     "@stylebysana",
    name:       "Sana Verhoeven",
    category:   "Fashion & Style",
    platform:   "TT",
    followers:  "211K",
    engagement: "8.9%",
    tags:       ["Thrifted","Capsule Wardrobe","OOTDs"],
    verified:   true,
    accent:     "#C8390F",
  }
];
