/**
 * VANTRA COLLECTIVE — TRENDING CREATORS ROSTER
 * Auto-generated by scripts/refresh-creators.mjs — do not edit by hand.
 * To change creators or static fields, edit scripts/creators-config.json.
 * Last refreshed: 2026-06-25T18:44:39.611Z
 */

export const LAST_UPDATED = 'June 2026';

export const TRENDING_CREATORS = [
  {
    featured:   true,
    handle:     "@alix.earle",
    name:       "Alix Earle",
    category:   "Lifestyle & Beauty",
    platform:   "TT",
    followers:  "7.9M",
    engagement: "15.4%",
    tags:       ["GRWM","College Life","Hauls"],
    verified:   true,
    accent:     "#E07B91",
  },

  {
    handle:     "@noel.deyzel",
    name:       "Noel Deyzel",
    category:   "Fitness & Physique",
    platform:   "TT",
    followers:  "2.5M",
    engagement: "11.2%",
    tags:       ["Bodybuilding","Training","Mindset"],
    verified:   true,
    accent:     "#5BA3FF",
  },

  {
    handle:     "@mkbhd",
    name:       "Marques Brownlee",
    category:   "Tech & Reviews",
    platform:   "YT",
    followers:  "19.2M",
    engagement: "4.8%",
    tags:       ["Gadgets","AI","Reviews"],
    verified:   true,
    accent:     "#9B72FF",
  },

  {
    handle:     "@nick.digiovanni",
    name:       "Nick DiGiovanni",
    category:   "Food & Culinary",
    platform:   "TT",
    followers:  "13.6M",
    engagement: "9.3%",
    tags:       ["Cooking","Records","Premium"],
    verified:   true,
    accent:     "#F0A535",
  },

  {
    handle:     "@wisdom.kaye",
    name:       "Wisdom Kaye",
    category:   "Fashion & Style",
    platform:   "TT",
    followers:  "5.3M",
    engagement: "8.1%",
    tags:       ["Menswear","Editorial","OOTDs"],
    verified:   true,
    accent:     "#C8390F",
  }
];
